config/routes.rb
G0::Application.routes.draw do

  match '/mail_accounts/index(/:test_mail)'  =>'mail_accounts#index',:as=>:mail_account_index
  match '/mail_accounts/tuiguang((/mode/:mode/way/sent)(/domain/:domain))'  =>'mail_accounts#tuiguang',:as=>:mail_account_tuiguang
  match '/mail_accounts/tuiguang/((/mode/:mode/way/receive)(/domain/:domain))'  =>'mail_accounts#receive',:as=>:mail_account_receive
  resources :mail_accounts

  resources :lib_companies

  resources :feedbacks
  match '/admin/hourscan'  =>'admin#hourscan',:as=>:adminhourscan
  match '/admin/hourscaninfo'  =>'admin#hourscaninfo',:as=>:adminhourscaninfo  
  match '/admin/move'  =>'admin#move',:as=>:adminmove
  match '/admin/moveinfo'  =>'admin#moveinfo',:as=>:adminmoveinfo  
  match '/admin/quzhougrasp'  =>'admin#quzhougrasp',:as=>:adminquzhougrasp
  match '/admin/tf56grasp'  =>'admin#tf56grasp',:as=>:admintf56grasp
  match '/admin/cargo_manage'  =>'admin#cargo_manage',:as=>:admincargo_manage
  match '/admin/stockcargo_manage'  =>'admin#stockcargo_manage' ,:as=>:adminstockcargo_manage
  match '/admin/truck_manage'  =>'admin#truck_manage',:as=>:admintruck_manage
  match '/admin/stocktruck_manage'  =>'admin#stocktruck_manage',:as=>:adminstocktruck_manage
  match '/admin/quote_manage'  =>'admin#quote_manage',:as=>:adminquote_manage
  match '/admin/usercontact_manage'  =>'admin#usercontact_manage',:as=>:adminusercontact_manage
  match '/admin/company_manage  '  =>'admin#company_manage' ,:as=>:admincompany_manage
  match '/admin/get_room_contact' =>'admin#get_room_contact' ,:as=>:admin_get_room_contact
  match '/admin/show_room_contact' =>'admin#show_room_contact' ,:as=>:admin_show_room_contact
  match '/admin/grasp_tf56' =>'admin#grasp_tf56' ,:as=>:admin_grasp_tf56
  match '/admin/grasp_quzhou' =>'admin#grasp_quzhou' ,:as=>:admin_grasp_quzhou
  match '/admin/scan' =>'admin#scan' ,:as=>:admin_scan
  match '/admin/scaninfo' =>'admin#scan_info' ,:as=>:admin_scan_info
  match '/admin/show_cron_mail' =>'admin#show_cron_mail' ,:as=>:admin_show_cron_mail
  match 'admin/daily_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#daily_trends' ,:as=>:admin_daily_trends
  match 'admin/hourly_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#hourly_trends' ,:as=>:admin_daily_trends
  match '/admin/request_log_analysis((/all/:all)(/logfile/:logfile))' =>'admin#request_log_analysis' ,:as=>:admin_request_log_analysis
  match '/admin/show_log(/logfile/:logfile)' =>'admin#show_log' ,:as=>:admin_show_log
  match '/admin/backup_db' =>'admin#backup_db' ,:as=>:admin_backup_db
  get "admin/index"

  resources :citystatistics

  get "quzhou_wuliu/index"
  get "quzhou_wuliu/show"

  match '/scans/uinfoscan'  =>'scans#uinfoscan',:as=>:scanuinfoscan
  match '/scans/expiretimer'  =>'scans#expiretimer',:as=>:scanexpiretimer
  match '/scans/truckexpire'  =>'scans#truckexpire',:as=>:scantruckexpire
  match '/scans/cargoexpire'  =>'scans#cargoexpire',:as=>:scancargoexpire
  match '/scans/scan'  =>'scans#scan',:as=>:scanscan
  match '/scans/scaninfo'  =>'scans#scaninfo',:as=>:scaninfo
  resources :scans

  resources :lstatistics

  resources :ustatistics

  resources :tstatistics

  resources :cstatistics

  match '/trucks/quoteinquery/:truck_id' =>'trucks#quoteinquery',:as=>:truckquoteinquery
  match '/cargos/quoteinquery/:cargo_id' =>'cargos#quoteinquery',:as=>:cargoquoteinquery
  match '/trucks/:truck_id/cargos/:cargo_id/inqueries/new'  =>'inqueries#new',:as=>:inquerienew
  match '/trucks/:truck_id/inqueries/truck' =>'inqueries#truck', :as=>:inquerietruck
  match '/cargos/:cargo_id/inqueries/cargo' =>'inqueries#cargo', :as=>:inqueriescargo
  match '/users/:user_id/inqueries/tome/:to' =>'inqueries#index',:as=>:inqueriesto
    match "/cargos/request_chenjiao/:id" =>'cargos#request_chenjiao',:as=>:cargorequest_chenjiao
  match "/trucks/confirm_chenjiao/:id" =>'trucks#confirm_chenjiao',:as=>:trucksconfirm_chenjiao
  resources :inqueries
  match '/cargos/search(/:from/:to(/:page))'  =>'cargos#search',:as=>:cargossearchline
  match '/cargos/:cargo_id/trucks/:truck_id/quotes/new'  =>'quotes#new',:as=>:quotesnew
  match '/cargos/:cargo_id/quotes/cargo' =>'quotes#cargo', :as=>:quotescargo
  match '/trucks/:truck_id/quotes/truck' =>'quotes#truck', :as=>:quotestruck
  match 'users/:user_id/quotes/tome/:to' =>'quotes#index',:as=>:quotesto
  resources :quotes

  resources :line_ads

  match 'searches/:user_id/:stype/' =>'searches#new',:as=>:searchespublicnew

  resources :searches

  get "public_main/index"


  match 'users/login' => 'users#login', :as => :userslogin
  match 'cargos/public' =>'cargos#public',:as=>:cargospublic
  match 'trucks/public' =>'trucks#public',:as=>:truckspublic

  match '/trucks/search/:from/:to/:page'  =>'trucks#search',:as=>:truckssearchline
  match '/trucks/request_chenjiao/:id' =>"trucks#request_chenjiao" ,:as=>:trucksrequest_chenjiao
  match '/trucks/index/:status' =>"trucks#index" ,:as=>:truckindexstatus
  match  '/trucks/new'=>'trucks#new',:as=>:trucksnew
  match  '/trucks/create'=>'trucks#create',:as=>:truckscreate
  match '/trucks/show' =>'trucks#show',:as=>:trucksshow
  match '/trucks/list/:id'=>'trucks#index',:as=>:trucksindex
  match '/trucks/:truck_id/match' =>'trucks#match', :as=>:trucksmatch
  resources :trucks do
    resources :inqueries
    resources :quotes
  end
  match '/companies/new/(:who)' =>'companies#new',:as=>:companiesnewwho
  match '/companies/index/:id(/:who)' =>'companies#index',:as=>:companiesindex
  match '/companies/showf/:id' =>'companies#showf',:as=>:companiesshowf
  match '/companies/show/:id/(:who)' =>'companies#show',:as=>:companiesshow
  match '/companies/search' =>'companies#search',:as=>:companiessearch
  match '/companies/create' =>'companies#create',:as=>:companiescreate
  match '/companies/admin' =>'companies#admin',:as=>:companiesadmin
  resources :companies

  match '/stock_trucks/:stock_truck_id/trucks/part' =>'trucks#part', :as=>:truckspart
  match  '/stock_trucks/oper/:id' =>'stock_trucks#oper',:as=>:stock_trucksoper
  match '/stock_trucks/create' =>'stock_trucks#create',:as=>:stock_truckscreate
  resources :stock_trucks do
    resources :trucks
  end

  match '/stock_cargos/:stock_cargo_id/cargos/part' =>'cargos#part', :as=>:cargospart
  match  '/stock_cargos/create' =>'stock_cargos#create', :as=>:stock_cargoscreate

  resources :stock_cargos  do
    resources :cargos
  end

  match 'cargos/request_chenjiao/:id'=>"cargos#request_chenjiao" ,:as=>:cargorequest_chenjiao
  match '/cargos/index/:status' =>"cargos#index" ,:as=>:cargoindexstatus
  match '/cargos/search' =>'cargos#search', :as=>:cargosrootsearch
  match '/cargos/new' =>'cargos#new', :as=>:cargosnew
  match '/cargos/create' =>'cargos#create', :as=>:cargoscreate
  match '/cargos/show' =>'cargos#show', :as=>:cargosshow
  match '/cargos/list/:id' =>'cargos#index', :as=>:cargosindex
  match '/cargos/:cargo_id/match' =>'cargos#match', :as=>:cargosmatch
  match '/cargos/destroy/:id' =>'cargos#destroy', :as=>:cargosdestroy
  
  resources :cargos do
    resources :quotes
    resources :inqueries
  end


  match  '/package_categories/show/:code' =>'package_categories#show',:as=>:package_categoriesshow
  resources :package_categories
  match '/user_contacts/showf/:id'=>'user_contacts#showf' , :as=>:usercontactsshowf
  match '/user_contacts/index/:id/(:who)'=>'user_contacts#index' , :as=>:usercontactsindex
  match '/user_contacts/user/:user_id'=>'user_contacts#show' , :as=>:usercontactsshow
  match '/user_contacts/edit'=>'user_contacts#edit' , :as=>:usercontactsedit
  match '/user_contacts/create' =>'user_contacts#create', :as=>:usercontactscreate
  resources :user_contacts

  match '/cargo_categories/show/:code'=>'cargo_categories#show',:as=>:cargo_categoriesshow
  resources :cargo_categories


  match '/cities/:dir(/:code)'=>'cities#index',:as=>:citiesindex
  resources :cities
  
  match 'users/contact' =>'users#contact',:as=>:userscontact
  match 'users/about' =>'users#about',:as=>:usersabout
  match 'users/mianze' =>'users#mianze',:as=>:usersmianze
  match 'users/login' =>'users#login',:as=>:userslogin
  match 'users/logout' =>'users#logout',:as=>:userslogout
  match 'users/pwreset' =>'users#pwreset',:as=>:userspwreset
  match 'users/authenticate' =>'users#authenticate',:as=>:usersauthenticate
  match '/users/activate/:name/:code' =>'users#activate',:as=>:usersactivate
  match '/users/pw_sent_confirm' =>'users#pw_sent_confirm',:as=>:userspwsentconfirm
  match '/users/pw_reset_request' =>'users#pw_reset_request',:as=>:userspwresetrequest
  match '/users/change_password_confirm/:username/:activate' =>'users#change_password_confirm',:as=>:usersactivate
  resources :users do
    resources :stock_cargos
    resources :stock_trucks
    resources :cargos
    resources :trucks
    resources :quotes
    resources :inqueries
    resources :companies
    resources :searchs
    resources :contact_people
  end











  root :to => "cargos#search"


  match ':controller(/:action(/:id(.:format)))'

end

app/models/inquery.rb
# coding: utf-8
class Inquery 
    include Mongoid::Document
    include Mongoid::Timestamps

    field :price,:type=>Integer
    field :comments,:type=>String

      #status
    field :status,:type=>String

   # foreign data
      field :cargo_id
      field :truck_id
      field :truck_company_id
      field :truck_user_id
      field :cargo_company_id
      field :cargo_user_id
      field :user_id
      
   #feature usage
      field :ismailed,:type=>Boolean
      field :isaccepted,:type=>Boolean
      index [[:cargo_id,Mongo::ASCENDING],[:truck_id,Mongo::ASCENDING]]

      validate :check_unique,:on=>:create
     
  def check_unique
    repeated=Inquery.where(:cargo_id=>self.cargo_id,:truck_id=>self.truck_id)
      unless repeated.size==0
      errors.add_to_base("不能重复询价")
      return false
    end
    return true
  end

end

app/controllers/inqueries_controller.rb
# coding: utf-8
class InqueriesController < ApplicationController
  # GET /inqueries
  # GET /inqueries.xml
  # layout "public"
  layout nil
  before_filter:authorize, :except => [:public]
  include CargosHelper
  include TrucksHelper
  
  def index
    @inqueries=Inquery.where(:user_id >session[:user_id]) 
    respond_to do |format|
      format.html # index.html.erb
      #  format.xml  { render :xml => @inqueries }
    end
  end

  def cargo
    @cargo=Cargo.find(params[:cargo_id])
    @bao_or_xun_record=Inquery.where(:cargo_id => params[:cargo_id])
    respond_to do |format|
      format.html # cargo.html.erb
      format.xml  { render :xml => @inqueries }
    end
  end

  #one trucks's all baojia
  def truck
    @truck=Truck.find(params[:truck_id])
    @bao_or_xun_record=Inquery.where(:truck_id => params[:truck_id])
    respond_to do |format|
      format.html # part.html.erb
      format.xml  { render :xml => @inqueries }
    end
  end
  
  def part
    
    unless params[:cargo_id].nil?
      @cargo=Cargo.find(params[:cargo_id])
      @inqueries=Inquery.where(:cargo_id =>params[:cargo_id],:user_id =>session[:user_id])
    end

    unless params[:truck_id].nil?
      @truck=Truck.find(params[:truck_id])
      @inqueries=Inquery.where(:truck_id =>params[:truck_id],:userb_id =>session[:user_id])
    end
   
    respond_to do |format|
      format.html # part.html.erb
      # format.xml  { render :xml =>@cargo }
    end
    
  end
 
  # GET /inqueries/1
  # GET /inqueries/1.xml
  def show
    @inquery = Inquery.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @inquery }
    end
  end

  # GET /inqueries/new
  # GET /inqueries/new.xml
  def new
    
    @inquery = Inquery.new
    @inquery.truck_id=params[:truck_id]
    @inquery.user_id=session[:user_id]

    @truck=Truck.find(@inquery.truck_id)

    @inquery.truck_user_id=@truck.user_id
    @inquery.truck_company_id=@truck.company_id

    @mycargo=Hash.new

    if params[:cargo_id].nil?
      @cargos = Cargo.where(:user_id =>session[:user_id].to_s,:status =>"正在配车")

      @cargos.each do |cargo|
        @mycargo[cargo.cate_name+"("+cargo.fcity_name+"<=>"+cargo.tcity_name+")"]=cargo.id
      end
     # logger.info "params cargo id =nil count=#{@mycargo.size}"
    else
      @cargo=Cargo.find(params[:cargo_id])
      @mycargo[@cargo.cate_name+"("+@cargo.fcity_name+"<=>"+@cargo.tcity_name+")"]=@cargo.id  
     # logger.info "params cargo id #{params[:cargo_id]}"
    end
   # logger.info "my cargo =#{@mycargo.to_a}"
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @inquery }
    end
  end

  # GET /inqueries/1/edit
  def edit
    @inquery = Inquery.find(params[:id])
    @cargos = Cargo.where(:user_id =>session[:user_id])
    @mycargo=Hash.new
    @cargos.each do |cargo|
      @mycargo[cargo.cate_name+"("+cargo.fcity_name+"<=>"+cargo.tcity_name+")"]=cargo.id
    end
  end

  # POST /inqueries
  # POST /inqueries.xml
  def create
     params[:inquery][:user_id]=session[:user_id]
     params[:inquery][:truck_id]=BSON::ObjectId(params[:inquery][:truck_id])
     params[:inquery][:cargo_id]=BSON::ObjectId(params[:inquery][:cargo_id])

    @inquery = Inquery.new(params[:inquery])
    if params[:mianyi]=="on"
      @inquery.price=nil
    end
      @cargo=Cargo.find(@inquery.cargo_id)
      @truck=Truck.find(@inquery.truck_id)

    @inquery.cargo_company_id=@cargo.company_id
    @inquery.cargo_user_id=@cargo.user_id
    @inquery.truck_company_id=@truck.company_id
    @inquery.truck_user_id=@truck.user_id

    respond_to do |format|
      #update statistic

      if @inquery.save
        if @cargo.from_site=="local"
         # before= Cstatistic.where({'cargo_id' => @inquery.cargo_id}).first.total_xunjia
         # before1= Tstatistic.where({'truck_id'=>@inquery.truck_id}).first.total_xunjia
        #  puts "更新询价统计cargo before=#{before},truck before=#{before1}"
          @cargo.inc(:total_xunjia,1)
          Truck.find(@inquery.truck_id).inc(:total_xunjia,1)
         # Cargo.collection.update({'_id' => @inquery.cargo_id},{'$inc' => {"total_xunjia" => 1}},{:upsert =>true}) 
         # Truck.collection.update({'_id'=>@inquery.truck_id},{'$inc' => {"total_xunjia" => 1}},{:upsert =>true})

          #  after= Cstatistic.where({'cargo_id' => @inquery.cargo_id}).first.total_xunjia
          #  after1=Tstatistic.where({'truck_id'=>@inquery.truck_id}).first.total_xunjia
          #  puts "更新询价统计 cargo after=#{after},truck after=#{after1}"
        end

        format.html { redirect_to(@inquery, :notice => '询价创建成功.') }
        format.xml  { render :xml => @inquery, :status => :created, :location => @inquery }
      else
        @inquery=nil
        flash[:notice]="创建询价失败，不能重复询价"
        format.html { render :action => "new" }
        format.xml  { render :xml => @inquery.errors, :status => :unprocessable_entity }
     end
    end
  end

  # PUT /inqueries/1
  # PUT /inqueries/1.xml
  def update
    @inquery = Inquery.find(params[:id])
    @truck=Truck.find(@inquery.truck_id)
    @inquery.paizhao=@truck.paizhao
    @inquery.fcity_name=@truck.fcity_name
    @inquery.tcity_name=@truck.tcity_name
    @cargos = Cargo.where(:user_id =>session[:user_id])
    @mycargo=Hash.new
    @cargos.each do |cargo|
      @mycargo[cargo.cate_name+"("+cargo.fcity_name+"<=>"+cargo.tcity_name+")"]=cargo.id
    end

    respond_to do |format|
      if @inquery.update_attributes(params[:inquery])
        format.html { redirect_to(@inquery, :notice => 'Inquery was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @inquery.errors, :status => :unprocessable_entity }
      end
    end
  end

  def request_chenjiao
     @inquery = Inquery.find(params[:id])
     #update truck status
     @truck=Truck.find(@inquery.truck_id)

     @truck.update_attributes(:status=>"邀请成交")

 
      #update cargo status

     @cargo=Cargo.find(@inquery.cargo_id)
     @cargo.update_attribute(:status,"邀请成交")

     @inquery.update_attributes(:status=>"邀请成交")

    #TOTO:notify all other related truck
    #All quotes to from this truck change to chenjiao
  
    @quotes=Quote.where("truck_id =? AND status =?",@truck.id,"正在配货")
    if  @quote.size>0
    @quotes.each do |quote|
      quote.update_attributes(:status=>"成交过期")
    end
    end
      #All Inquers from this cargo neec change to chenjiao
       @inqueries=Inquery.where(:cargo_id =>@cargo.id,:status =>"正在配货")
    if  @inqueries.size>0
      @inqueries.each do |inquery|
      inquery.update_attributes(:status=>"成交过期")
    end
    end


     respond_to do |format|
        format.html { redirect_to(:controller=>"cargos",:action=>"index" )}
    end
    
  end

  def confirm_chenjiao
    
  end

  # DELETE /inqueries/1
  # DELETE /inqueries/1.xml
  def destroy
    @inquery = Inquery.find(params[:id])
    @inquery.destroy

    respond_to do |format|
      format.html { redirect_to(inqueries_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/inqueries_helper.rb
module InqueriesHelper
end

app/views/inqueries/_form.html.erb
<%if @mycargo.size>0%>
<%= form_for(@inquery,:as=>:inquery,:html => {:class => "show_form"}) do |f| %>
  <% if @inquery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquery.errors.count, "error") %> prohibited this inquery from being saved:</h2>

      <ul>
      <% @inquery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%#=render "trucks/title"%>
  <div class="field2">
    <%= f.label :出价 %>
    <%= f.text_field :price %>元,
   <label  style="width:20px;">面议</label><input  style="width:20px;" id="mianyi" name="mianyi" type="checkbox"></input>
</div>
<!--
  <div class="field">
    <%= f.label :备注 %>
    <%= f.text_field :comments %>
  </div>
-->
  <div class="field2">
    <%= f.label :我的货物及其线路 %>
    <%#= f.text_field :cargo_id %>
     <%= f.select(:cargo_id,options_for_select(@mycargo.to_a,@inquery.cargo_id) ) %>
  <%= f.submit("确定") %>
  </div>

    <%= f.hidden_field :truck_id %>
    <%= f.hidden_field :user_id %>
    <%#= f.hidden_field :truck_user_id %>
    <%#= f.hidden_field :truck_company_id %>


  <div class="actions">
   
  </div>
<% end %>
<%else%>
<p>你不能询价， 你没有正在配车的货源</p>
<%end%>

app/views/inqueries/_list.html.erb

<table>
  <tr>
    <th>车源拍照</th>
    <th>车源联系</th>
    <th>出价</th>
    <th>出发</th>
    <th>到达</th> 
    <th>出价时间</th>
    <th>询价货源</th>
    <th>管理</th>
  </tr>
  <% unless @inqueries.nil?%>

    <% @inqueries.each do |inquery| %>
      <tr>
        <td><%=link_to "#{inquery.paizhao}", truck_path(inquery.truck_id),:class=>"show_float"%></td>
        <td><%=link_to "#{inquery.user_name}", user_path(inquery.user_id),:class=>"show_float" unless inquery.user_id.nil?%>|
        <%=link_to "#{inquery.company_name}", company_path(inquery.company_id),:class=>"show_float"unless inquery.company_id.nil?%>
        </td>
        <td><%= inquery.price %></td>
        <td><%= inquery.fcity_name %></td>
        <td><%= inquery.tcity_name %></td>
        <td><%= inquery.created_at %></td>
        <td><%= link_to "#{inquery.cate_name}", cargo_path(inquery.cargo_id) %></td>

        <td>
          <a  class ="navi_link" href="/users/<%=session[:user_id]%>/cargos/<%=inquery.cargo_id%>/match">继续询价</a>|
          <%= link_to '编辑', edit_inquery_path(inquery) %>|
          <a href="/inqueries/destroy/<%inquery.id%>">删除</a>
          </td>
      </tr>
    <% end %>
  <% end %>
</table>

<br />




app/views/inqueries/cargo.html.erb
<%=render "shared/cargo"%>

app/views/inqueries/edit.html.erb
<h1>Editing inquery</h1>

<%= render 'form' %>

<%= link_to 'Show', @inquery %> |
<%= link_to 'Back', inqueries_path %>

app/views/inqueries/index.html.erb

<h1>车主询价</h1>

<table>
  <tr>
    <th>车源牌照</th>
    <th>车源联系</th>
    <th>出价</th>
    <th>出发</th>
    <th>到达</th> 
    <th>出价时间</th>
    <th>询价货源</th>
    <th>管理</th>
  </tr>
  <% unless @inqueries.blank?%>

    <% @inqueries.each do |inquery| %>
      <tr>
        <td><%=link_to "#{inquery.paizhao}", truck_path(inquery.truck_id),:class=>"show_float"%></td>
        <td><%=link_to "#{inquery.user_name}", user_path(inquery.user_id),:class=>"show_float" unless inquery.user_id.nil?%>|
        <%=link_to "#{inquery.company_name}", company_path(inquery.company_id),:class=>"show_float"unless inquery.company_id.nil?%>
        </td>
        <td>
<%= inquery.price ||"面议"%>
        </td>
        <td><%= inquery.fcity_name %></td>
        <td><%= inquery.tcity_name %></td>
        <td><%= inquery.created_at %></td>
        <td><%= link_to "#{inquery.cate_name}", cargo_path(inquery.cargo_id) %></td>

        <td>
          <a  class ="navi_link" href="/users/<%=session[:user_id]%>/cargos/<%=inquery.cargo_id%>/match">继续询价</a>|
          <%= link_to '编辑', edit_inquery_path(inquery) %>|
          <a href="/inqueries/destroy/<%inquery.id%>">删除</a>
          </td>
      </tr>
    <% end %>
  <% end %>
</table>

<br />



<%#= link_to 'New Inquery', new_inquery_path %>

app/views/inqueries/new.html.erb
<span class="baojia_new">
<%unless @inquery.blank?%>
<%= render 'form' %>
<%else%>
  <p id="notice"><%= notice %></p>
<%end%>

<%#= link_to 'Back', inqueries_path %>
</span>

app/views/inqueries/part.html.erb
<%unless @cargo.nil?%>
<p><%=@cargo.cate_name%>发出的全部询价:</p>
<%end%>
<%unless @truck.nil?%>
<p><%=@truck.paizhao%>收到的全部询价:</p>
<%end%>

<%=render "list"%>





app/views/inqueries/show.html.erb


<p id="notice"><%= notice %></p>
<div>
<p>
  <b>报价:</b>
  <%= @inquery.price %>
</p>

<%#= link_to 'Edit', edit_inquery_path(@inquery) %> |
<%#= link_to 'Back', inqueries_path %>
</div>

app/views/inqueries/truck.html.erb
<%=render "shared/truck"%>