config/routes.rb
G0::Application.routes.draw do

  match '/mail_accounts/index(/:test_mail)'  =>'mail_accounts#index',:as=>:mail_account_index
  match '/mail_accounts/tuiguang((/mode/:mode/way/sent)(/domain/:domain))'  =>'mail_accounts#tuiguang',:as=>:mail_account_tuiguang
  match '/mail_accounts/tuiguang/((/mode/:mode/way/receive)(/domain/:domain))'  =>'mail_accounts#receive',:as=>:mail_account_receive
  resources :mail_accounts

  resources :lib_companies

  resources :feedbacks
  match '/admin/hourscan'  =>'admin#hourscan',:as=>:adminhourscan
  match '/admin/hourscaninfo'  =>'admin#hourscaninfo',:as=>:adminhourscaninfo  
  match '/admin/move'  =>'admin#move',:as=>:adminmove
  match '/admin/moveinfo'  =>'admin#moveinfo',:as=>:adminmoveinfo  
  match '/admin/quzhougrasp'  =>'admin#quzhougrasp',:as=>:adminquzhougrasp
  match '/admin/tf56grasp'  =>'admin#tf56grasp',:as=>:admintf56grasp
  match '/admin/cargo_manage'  =>'admin#cargo_manage',:as=>:admincargo_manage
  match '/admin/stockcargo_manage'  =>'admin#stockcargo_manage' ,:as=>:adminstockcargo_manage
  match '/admin/truck_manage'  =>'admin#truck_manage',:as=>:admintruck_manage
  match '/admin/stocktruck_manage'  =>'admin#stocktruck_manage',:as=>:adminstocktruck_manage
  match '/admin/quote_manage'  =>'admin#quote_manage',:as=>:adminquote_manage
  match '/admin/usercontact_manage'  =>'admin#usercontact_manage',:as=>:adminusercontact_manage
  match '/admin/company_manage  '  =>'admin#company_manage' ,:as=>:admincompany_manage
  match '/admin/get_room_contact' =>'admin#get_room_contact' ,:as=>:admin_get_room_contact
  match '/admin/show_room_contact' =>'admin#show_room_contact' ,:as=>:admin_show_room_contact
  match '/admin/grasp_tf56' =>'admin#grasp_tf56' ,:as=>:admin_grasp_tf56
  match '/admin/grasp_quzhou' =>'admin#grasp_quzhou' ,:as=>:admin_grasp_quzhou
  match '/admin/scan' =>'admin#scan' ,:as=>:admin_scan
  match '/admin/scaninfo' =>'admin#scan_info' ,:as=>:admin_scan_info
  match '/admin/show_cron_mail' =>'admin#show_cron_mail' ,:as=>:admin_show_cron_mail
  match 'admin/daily_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#daily_trends' ,:as=>:admin_daily_trends
  match 'admin/hourly_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#hourly_trends' ,:as=>:admin_daily_trends
  match '/admin/request_log_analysis((/all/:all)(/logfile/:logfile))' =>'admin#request_log_analysis' ,:as=>:admin_request_log_analysis
  match '/admin/show_log(/logfile/:logfile)' =>'admin#show_log' ,:as=>:admin_show_log
  match '/admin/backup_db' =>'admin#backup_db' ,:as=>:admin_backup_db
  get "admin/index"

  resources :citystatistics

  get "quzhou_wuliu/index"
  get "quzhou_wuliu/show"

  match '/scans/uinfoscan'  =>'scans#uinfoscan',:as=>:scanuinfoscan
  match '/scans/expiretimer'  =>'scans#expiretimer',:as=>:scanexpiretimer
  match '/scans/truckexpire'  =>'scans#truckexpire',:as=>:scantruckexpire
  match '/scans/cargoexpire'  =>'scans#cargoexpire',:as=>:scancargoexpire
  match '/scans/scan'  =>'scans#scan',:as=>:scanscan
  match '/scans/scaninfo'  =>'scans#scaninfo',:as=>:scaninfo
  resources :scans

  resources :lstatistics

  resources :ustatistics

  resources :tstatistics

  resources :cstatistics

  match '/trucks/quoteinquery/:truck_id' =>'trucks#quoteinquery',:as=>:truckquoteinquery
  match '/cargos/quoteinquery/:cargo_id' =>'cargos#quoteinquery',:as=>:cargoquoteinquery
  match '/trucks/:truck_id/cargos/:cargo_id/inqueries/new'  =>'inqueries#new',:as=>:inquerienew
  match '/trucks/:truck_id/inqueries/truck' =>'inqueries#truck', :as=>:inquerietruck
  match '/cargos/:cargo_id/inqueries/cargo' =>'inqueries#cargo', :as=>:inqueriescargo
  match '/users/:user_id/inqueries/tome/:to' =>'inqueries#index',:as=>:inqueriesto
    match "/cargos/request_chenjiao/:id" =>'cargos#request_chenjiao',:as=>:cargorequest_chenjiao
  match "/trucks/confirm_chenjiao/:id" =>'trucks#confirm_chenjiao',:as=>:trucksconfirm_chenjiao
  resources :inqueries
  match '/cargos/search(/:from/:to(/:page))'  =>'cargos#search',:as=>:cargossearchline
  match '/cargos/:cargo_id/trucks/:truck_id/quotes/new'  =>'quotes#new',:as=>:quotesnew
  match '/cargos/:cargo_id/quotes/cargo' =>'quotes#cargo', :as=>:quotescargo
  match '/trucks/:truck_id/quotes/truck' =>'quotes#truck', :as=>:quotestruck
  match 'users/:user_id/quotes/tome/:to' =>'quotes#index',:as=>:quotesto
  resources :quotes

  resources :line_ads

  match 'searches/:user_id/:stype/' =>'searches#new',:as=>:searchespublicnew

  resources :searches

  get "public_main/index"


  match 'users/login' => 'users#login', :as => :userslogin
  match 'cargos/public' =>'cargos#public',:as=>:cargospublic
  match 'trucks/public' =>'trucks#public',:as=>:truckspublic

  match '/trucks/search/:from/:to/:page'  =>'trucks#search',:as=>:truckssearchline
  match '/trucks/request_chenjiao/:id' =>"trucks#request_chenjiao" ,:as=>:trucksrequest_chenjiao
  match '/trucks/index/:status' =>"trucks#index" ,:as=>:truckindexstatus
  match  '/trucks/new'=>'trucks#new',:as=>:trucksnew
  match  '/trucks/create'=>'trucks#create',:as=>:truckscreate
  match '/trucks/show' =>'trucks#show',:as=>:trucksshow
  match '/trucks/list/:id'=>'trucks#index',:as=>:trucksindex
  match '/trucks/:truck_id/match' =>'trucks#match', :as=>:trucksmatch
  resources :trucks do
    resources :inqueries
    resources :quotes
  end
  match '/companies/new/(:who)' =>'companies#new',:as=>:companiesnewwho
  match '/companies/index/:id(/:who)' =>'companies#index',:as=>:companiesindex
  match '/companies/showf/:id' =>'companies#showf',:as=>:companiesshowf
  match '/companies/show/:id/(:who)' =>'companies#show',:as=>:companiesshow
  match '/companies/search' =>'companies#search',:as=>:companiessearch
  match '/companies/create' =>'companies#create',:as=>:companiescreate
  match '/companies/admin' =>'companies#admin',:as=>:companiesadmin
  resources :companies

  match '/stock_trucks/:stock_truck_id/trucks/part' =>'trucks#part', :as=>:truckspart
  match  '/stock_trucks/oper/:id' =>'stock_trucks#oper',:as=>:stock_trucksoper
  match '/stock_trucks/create' =>'stock_trucks#create',:as=>:stock_truckscreate
  resources :stock_trucks do
    resources :trucks
  end

  match '/stock_cargos/:stock_cargo_id/cargos/part' =>'cargos#part', :as=>:cargospart
  match  '/stock_cargos/create' =>'stock_cargos#create', :as=>:stock_cargoscreate

  resources :stock_cargos  do
    resources :cargos
  end

  match 'cargos/request_chenjiao/:id'=>"cargos#request_chenjiao" ,:as=>:cargorequest_chenjiao
  match '/cargos/index/:status' =>"cargos#index" ,:as=>:cargoindexstatus
  match '/cargos/search' =>'cargos#search', :as=>:cargosrootsearch
  match '/cargos/new' =>'cargos#new', :as=>:cargosnew
  match '/cargos/create' =>'cargos#create', :as=>:cargoscreate
  match '/cargos/show' =>'cargos#show', :as=>:cargosshow
  match '/cargos/list/:id' =>'cargos#index', :as=>:cargosindex
  match '/cargos/:cargo_id/match' =>'cargos#match', :as=>:cargosmatch
  match '/cargos/destroy/:id' =>'cargos#destroy', :as=>:cargosdestroy
  
  resources :cargos do
    resources :quotes
    resources :inqueries
  end


  match  '/package_categories/show/:code' =>'package_categories#show',:as=>:package_categoriesshow
  resources :package_categories
  match '/user_contacts/showf/:id'=>'user_contacts#showf' , :as=>:usercontactsshowf
  match '/user_contacts/index/:id/(:who)'=>'user_contacts#index' , :as=>:usercontactsindex
  match '/user_contacts/user/:user_id'=>'user_contacts#show' , :as=>:usercontactsshow
  match '/user_contacts/edit'=>'user_contacts#edit' , :as=>:usercontactsedit
  match '/user_contacts/create' =>'user_contacts#create', :as=>:usercontactscreate
  resources :user_contacts

  match '/cargo_categories/show/:code'=>'cargo_categories#show',:as=>:cargo_categoriesshow
  resources :cargo_categories


  match '/cities/:dir(/:code)'=>'cities#index',:as=>:citiesindex
  resources :cities
  
  match 'users/contact' =>'users#contact',:as=>:userscontact
  match 'users/about' =>'users#about',:as=>:usersabout
  match 'users/mianze' =>'users#mianze',:as=>:usersmianze
  match 'users/login' =>'users#login',:as=>:userslogin
  match 'users/logout' =>'users#logout',:as=>:userslogout
  match 'users/pwreset' =>'users#pwreset',:as=>:userspwreset
  match 'users/authenticate' =>'users#authenticate',:as=>:usersauthenticate
  match '/users/activate/:name/:code' =>'users#activate',:as=>:usersactivate
  match '/users/pw_sent_confirm' =>'users#pw_sent_confirm',:as=>:userspwsentconfirm
  match '/users/pw_reset_request' =>'users#pw_reset_request',:as=>:userspwresetrequest
  match '/users/change_password_confirm/:username/:activate' =>'users#change_password_confirm',:as=>:usersactivate
  resources :users do
    resources :stock_cargos
    resources :stock_trucks
    resources :cargos
    resources :trucks
    resources :quotes
    resources :inqueries
    resources :companies
    resources :searchs
    resources :contact_people
  end











  root :to => "cargos#search"


  match ':controller(/:action(/:id(.:format)))'

end

app/models/cargo.rb
# coding: utf-8
class  Cargo
   include Mongoid::Document
   include Mongoid::Timestamps
    # cattr_reader :per_page
    # @@per_page = 20      
   # cargo self info
      field :cargo_weight, :type=>String
      field :cargo_zuhuo, :type=>String
      field :cargo_bulk, :type=>String
      field :send_date, :type=>String
      field :comments, :type=>String
      field :status, :type=>String

      #for not go back to find stock_cargo
      field :cate_name, :type=>String
      field :package_name, :type=>String
      field :big_category, :type=>String

      # important line info
      field :line, :type=>String
      field :fcity_name, :type=>String
      field :tcity_name, :type=>String
      field :fcity_code, :type=>String
      field :tcity_code, :type=>String   

      #important information
      field :zhuang_addr, :type=>String
      field :zhuang_time, :type=>String
      field :xie_addr, :type=>String
      
      field :price, :type=>String
      field :price_unit, :type=>String
      
  # from site
      field :from_site, :type=>String
     
    # statistic
      field :total_baojia, :type=>Integer
      field :total_xunjia, :type=>Integer
      field :total_match, :type=>Integer
      field :total_click, :type=>Integer
      
      field :cj_truck_id
      field :cj_quote_id
      field :cj_user_id
      field :cj_company_id
      
    #future usage
      field :user_id
      field :user_contact_id
      field :company_id
     field :stock_cargo_id

      
     index ([[:updated_at,Mongo::ASCENDING],[:status,Mongo::ASCENDING],[:fcity_code,Mongo::ASCENDING],[:tcity_code,Mongo::ASCENDING]])
    validates_presence_of :fcity_code,:tcity_code   #remove cate_name, could be empty from grasp
    validate :check_unique,:on=>:create
  def check_unique
       repeated=Cargo.where(:cate_name=>self.cate_name,:line=>self.line,:user_id=>self.user_id,:status=>"正在配车",
                  :comments=>self.comments,:from_site=>self.from_site )
       unless repeated.size==0
      errors.add(:base,"不能重复发布货源信息")
     return false
    end
    return true
  end
     
end

app/helpers/cargos_helper.rb
 # coding: utf-8
 


module CargosHelper
    include FileUtils
 def get_max_min_code(code)
    max_code,min_code=0

   if code.match(/\d\d0000000000$/) # is a province id 
         max_code=(code.to_i+10000000000).to_s     
         min_code=code
         iscity=false
   elsif code.match(/\d\d\d\d00000000$/)  and (not code.match(/\d\d0000000000$/))  # is a region
        iscity=false
        max_code=(code.to_i+100000000).to_s
        min_code=code
   else
       iscity=true
       max_code=code
       min_code=code
   end
  # puts "code=#{code},min_code=#{min_code},max_code=#{max_code},iscity=#{iscity}"
   [min_code,max_code,iscity]   
  end

 #for view storage purpose, but now use page cache 
 def get_search_cargos(fcity_code,tcity_code)
   
   if fcity_code=="100000000000" && tcity_code=="100000000000" then
       @cargos=Cargo.where(:status=>"正在配车").desc(:updated_at).paginate(:page=>params[:page]||1,:per_page=>20)
    elsif fcity_code=="100000000000" && tcity_code!="100000000000"
      result=get_max_min_code(tcity_code)
      min=result[0]
      max=result[1]
      if result[2]
        @cargos=Cargo.where({:tcity_code=>min,:status=>"正在配车"}).desc(:updated_at).paginate(:page=>params[:page]||1,:per_page=>20)
      else
        @cargos=Cargo.where({:tcity_code.gte=>min,:tcity_code.lt=>max,:status=>"正在配车"}).desc(:updated_at).paginate(:page=>params[:page]||1,:per_page=>20)
       end
     elsif tcity_code=="100000000000" && fcity_code!="100000000000"
      result=get_max_min_code(fcity_code)
      min=result[0]
      max=result[1]
      if result[2]
        @cargos=Cargo.where({:fcity_code=>min,:status=>"正在配车"}).desc(:updated_at).paginate(:page=>params[:page]||1,:per_page=>20)
      else
        @cargos=Cargo.where({:fcity_code.gte =>min,:fcity_code.lt =>max,:status=>"正在配车"}).desc(:updated_at).paginate(:page=>params[:page]||1,:per_page=>20)
      end
    else
   
     resultt=get_max_min_code(tcity_code)
      mint=resultt[0]
      maxt=resultt[1]
    
     resultf=get_max_min_code(fcity_code)
      minf=resultf[0]
      maxf=resultf[1]

    #  puts "mint=#{mint}, maxt=#{maxt},minf=#{minf},maxf=#{maxf},resultt[2]=#{resultt[2]},resultf=#{resultf[2]}"
      if resultt[2]==false && resultf[2]==false  
        @cargos=Cargo.where({:fcity_code.gte =>minf,:fcity_code.lt =>maxf,:tcity_code.gte=>mint,:tcity_code.lt=>maxt,:status=>"正在配车"}).desc(:updated_at).paginate(:page=>params[:page]||1,:per_page=>20)
      elsif resultt[2]==true && resultf[2]==false  
        @cargos=Cargo.where({:fcity_code.gte =>minf,:fcity_code.lt =>maxf,:tcity_code=>mint,:status=>"正在配车"}).desc(:updated_at).paginate(:page=>params[:page]||1,:per_page=>20)
      elsif resultt[2]==false && resultf[2]==true
        @cargos=Cargo.where({:fcity_code=>minf,:tcity_code.gte=>mint,:tcity_code.lt=>maxt,:status=>"正在配车"}).desc(:updated_at).paginate(:page=>params[:page]||1,:per_page=>20)
      else
        @cargos=Cargo.where(:fcity_code =>minf,:tcity_code=>mint,:status=>"正在配车").desc(:created_at).paginate(:page=>params[:page]||1,:per_page=>20)
        end
    end
    @cargos
 end
 
 def expire_line_cargo(from_city,to_city)   
   lines=Array.new
  if (from_city!="100000000000" && to_city!="100000000000")
    lines<<[from_city,to_city] #expire city to city 
    lines<<[from_city.slice(0,4)+"00000000",to_city] #expire region to city
    lines<<[from_city.slice(0,2)+"0000000000",to_city] #province to city
    lines<<["100000000000",to_city] #expire anywhere  to city  
    lines<<["100000000000",to_city.slice(0,4)+"00000000"] #expire anywhere  to region  
    lines<<["100000000000",to_city.slice(0,2)+"0000000000"] #expire anywhere to province  
     
    lines<<[from_city,to_city.slice(0,4)+"00000000"] #city to region
    lines<<[from_city,to_city.slice(0,2)+"0000000000"] #city  to province
    lines<<[from_city,"100000000000"]  #expire city to anywhere
    lines<<[from_city.slice(0,4)+"00000000","100000000000"]  #expire region to anywhere
    lines<<[from_city.slice(0,2)+"0000000000","100000000000"]  #expire province to anywhere
    
   lines<<[from_city.slice(0,4)+"00000000",to_city.slice(0,4)+"00000000"] #expire region to region 
   lines<<[from_city.slice(0,2)+"0000000000",to_city.slice(0,2)+"0000000000"] #expire province to province 
   lines<<[from_city.slice(0,4)+"00000000",to_city.slice(0,2)+"0000000000"] #expire region to province 
   lines<<[from_city.slice(0,2)+"0000000000",to_city.slice(0,4)+"00000000"] #expire province  to region 
  
  
   all_lines=lines.uniq
  
   #rm folder
   all_lines.each do |line|
     FileUtils.rm_rf Rails.public_path+"/cargos/search"+"/#{line[0]}"+"/#{line[1]}"       
     Rails.logger.debug "expire "+Rails.public_path+"/cargos/search"+"/#{line[0]}"+"/#{line[1]}"
   end
  else
    #only expire first page, others only Cargos.count/ % 20 ==0 to expire
    # if Cargo.count % 20 ==0
    #    FileUtils.rm_rf Rails.public_path+"/cargos/search"+"/#{line[0]}"+"/#{line[1]}"   
    # else
   #     FileUtils.rm_rf Rails.public_path+"/cargos/search"+"/#{line[0]}"+"/#{line[1]}/1.html"       
   #  end
    end
 end



end

app/views/cargos/_cargolist.html.erb
  
 <%@cargos=get_search_cargos(@search.fcity_code,@search.tcity_code)%>


 <table>  
 <th>货物</th>      
     <th>
      <a id="from_data_load"  href="/cities/from/<%=@search.fcity_code%>"><%=@search.fcity_name ||"出发地选择"%></a>
    </th>
<th>
      <a  id="to_data_load"  href="/cities/to/<%=@search.tcity_code%>" ><%=@search.tcity_name ||"到达地选择"%></a>
</th>
      <th>重量</th>
      <th>有效期</th>      
      <th>发布日期</th>
      <th>货源状态</th>    
      <th>车主操作</th>
  <th style="background-color:#F2F2F2;" class="search">
    
   <input value="查询" class="cargo_search" type="submit" name="asss">
   
   <!--  <a id="search"  href=<%="/cargos/search/#{@search.fcity_code}/#{@search.tcity_code}/1"%>>查询</a>-->
     
  </th>

 <% unless @cargos.blank? %>
    <% @cargos.each do |cargo| %>
      <%unless cargo.nil? %>
        <tr>
          <td ><a class ="show_float" href="/cargos/show/<%=cargo.id%>">
           <%= cargo.cate_name ||"未知货物"%></a> </td>
          <td ><%= cargo.fcity_name %></td>
          <td ><%= cargo.tcity_name %></td>
          <td><%= cargo.cargo_weight || "0" %>吨/<%= cargo.cargo_bulk ||0 %>方</td>
          <td><%= cargo.send_date %>天</td>
          <!--
          <td><%= cargo.package_name %></td>        
          <td><%=h $cargo_big_category[cargo.big_category]%></td>
          <td><%= h $cargo_option[cargo.cargo_zuhuo] %></td>
        
          <td><%=cargo.updated_at.localtime.to_s.slice(0,19) unless cargo.updated_at.nil? %></td>       -->
          <td><%=cargo.created_at.localtime.to_s.slice(0,19) unless cargo.updated_at.nil? %></td>
          <td><%=cargo.status %></td>
          <td>
            <%if cargo[:from_site]=="local"%>
            <%unless session[:user_id].nil?%>
            <%if cargo.user_id==session[:user_id]%>
             货主
            <%else%>
                <a class="baojia" href="/cargos/<%=cargo.id%>/quotes/new">报价</a>
             <%end%>
            <%else%>
            登录后报价
            <%end%>
            <%else%>
            其他
            <%end%>
           </td>               
        </tr>
      <% end %>
    <% end %>
  </table>

<%= will_paginate @cargos ,:action=>"search",:params=>{:from=>@search.fcity_code, :to=>@search.tcity_code}%>

<%else%>
  <p>
    不好意思，没有对应的货源.
  </p>

<%end %>



  




app/views/cargos/_cargonavi.html.erb

<%#coding:utf-8%>

<div class="bottom_link">

<a class="page_navi_link" href="/cargos/index/peiche">正在配车(<%=(@user.ustatistic.valid_cargo if @user)||0%>)</a>
<a class="page_navi_link" href="/cargos/index/ischenjiao">正在成交</a>
<a style="margin-right: 50px" class="page_navi_link" href="/cargos/index/chenjiao">已成交</a>
<!--<a class="page_navi_link" href="/cargos/index/过期">过期货源</a>
<a class="page_navi_link" href="/cargos/">全部货源</a>-->
  <%= link_to '继续发布货源', stock_cargos_path %>
<a  href="/stock_cargos/new">添加新的货物</a>

</div>


app/views/cargos/_form.html.erb

<%= form_for(@cargo,@stock_cargo,:as=>:cargo,:html => {:class => "show_form"}) do |f| %>
  <% if @cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cargo.errors.count, "错误") %></h2>
      <ul>
        <% @cargo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    
  <div class="line">
      <h3><%=@stock_cargo.cate_name%>,<%=@stock_cargo.package_name%>包装, 货源发布</h3>
  <!-- do not change below  format -->
      <label class="line_from_label" >出发地*:</label>
      <a id="from_data_load" style="display:inline;" href="/cities/from"><%=(@cargo.fcity_name.nil?||@cargo.fcity_name.empty?) ?"请选择出发地":@cargo.fcity_name%></a>
      <%= f.hidden_field(:fcity_code) %>
      <%= f.hidden_field(:fcity_name) %>
      
      <label style="margin-left:20px;display:inline;" class="line_to_label " >到达地*:</label>
       <a id="to_data_load" style="display:inline;" href="/cities/to" ><%=(@cargo.tcity_name.nil?||@cargo.tcity_name.empty?) ?"请选择到达地":@cargo.tcity_name%></a>
      <%= f.hidden_field(:tcity_code) %>
      <%= f.hidden_field(:tcity_name) %>
   
  <!-- do not change this format -->
</div>
    

  <%= f.hidden_field(:cate_name, :value=>@stock_cargo.cate_name) %>
  <%= f.hidden_field(:package_name, :value=>@stock_cargo.package_name) %>
  <%= f.hidden_field(:big_category, :value=>@stock_cargo.big_category) %>

   <%= f.hidden_field :status%>
     <div class="field">
      <label >重量(吨)*</label>
      <%= f.text_field :cargo_weight %> 
     </div>
    
     <div class="field">
      <label>体积(方)</label>
       <%= f.text_field :cargo_bulk %>
     </div>
    
     <div class="field">
     <label>有效天数*</label>
     <%= f.select(:send_date,options_for_select([["一天","1"],["当天","0"],["二天","2"]],@cargo.send_date) )%>
     </div>
     <div class="field">
     <label for="cargo_option">组货方式*：</label>
     <%= f.select(:cargo_zuhuo,options_for_select($cargo_option_reverse.to_a,@cargo.cargo_zuhuo) )%>
     </div>

   <div class="field">
    <label >联系人：</label>
    <%=(@user_contact||@user).name%>
   </div>

   <div class="field">
    <label >联系电话：</label>
    <%=(@user_contact||@user).mobilephone||"无"%>
   </div>

    <div class="actions">
       <%= f.submit("确定") %>
    </div>   

    <%= f.hidden_field :stock_cargo_id%>
<p>*号为必填项</p>
  <% end %>

<div>
<p id="notice"><%= notice %></p>
</div>

app/views/cargos/_qzshow.html.erb

  <div id="cargo_show" >
 <table>
   <tr>
    <th>价格</th>
    <th>联系电话</th>
    <th>备注</th>
  </tr>
  <tr>
<td>

 <%=@cargo.price %><%=@cargo.price_unit %>
</td>
<td>
 <%=@cargo.contact_phone %>
</td>
<td>
 <%= @cargo.comments %>
</td>
</tr>
</table>
</div>




app/views/cargos/_search.html.erb
<h3>物流零距离--共找到<%=@cargos.size unless @cargos.nil?%>条货源信息</h3>
<%= render '/searches/cform' %>

<%=render '/cargos/cargolist'%>

app/views/cargos/_title.html.erb

<h3>
  <%= @cargo.cate_name %>
  (
  <%= @cargo.fcity_name %>
  ==>
  <%= @cargo.tcity_name %>),
  <%=@cargo.cargo_weight%>吨<%=@cargo.cargo_bulk%>方,
  <%=@cargo.status%>
</h3>





app/views/cargos/chenjiao.html.erb
<div >

<div> <h2>货物信息</h2></div>
<div> <h2>货物发布人信息</h2></div>
<div> <h2>货物发布人公司信息</h2></div>
<div> <h2>车辆信息</h2></div>
<div> <h2>车辆发布人信息</h2></div>
<div> <h2>车辆发布人公司信息</h2></div>

</div>

app/views/cargos/edit.html.erb
<h1>Editing cargo</h1>

<%= render 'form' %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargos_path %>

app/views/cargos/match.html.erb
<div class="form_header">
<%=render "cargos/title"%>
</div>
<%=render "/trucks/trucklist"%>
<%#= link_to 'New Truck', new_truck_path %>

app/views/cargos/new.html.erb
<div class="cargo_new">
<%= render 'form' %>
</div>
<%#= link_to 'Back', cargos_path %>

app/views/cargos/part.html.erb
<h1><%=@stock_cargo.cate_name%>的全部货源</h1>

<%= render 'list' %>


<p>
  <%= link_to '请到这里发布货源', stock_cargos_path,:class=>"page_navi_link" %>
|
  <%= link_to '全部货物', stock_cargos_path,:class=>"page_navi_link" %>
|
  <%= link_to '全部货源', cargos_path,:class=>"page_navi_link" %>
</p>

app/views/cargos/repeat_error.html.erb


<p>不能重复发布货源</p>

app/views/cargos/search.html.erb

<%#= render '/searches/cform' %>
 <%#= cache(:action=>"search", :layout=>nil,:action_suffix =>"cargo#{@action_suffix}") do %>
<%=render '/cargos/cargolist'%>
<%#=end%>