config/routes.rb
G0::Application.routes.draw do

  match '/mail_accounts/index(/:test_mail)'  =>'mail_accounts#index',:as=>:mail_account_index
  match '/mail_accounts/tuiguang((/mode/:mode/way/sent)(/domain/:domain))'  =>'mail_accounts#tuiguang',:as=>:mail_account_tuiguang
  match '/mail_accounts/tuiguang/((/mode/:mode/way/receive)(/domain/:domain))'  =>'mail_accounts#receive',:as=>:mail_account_receive
  resources :mail_accounts

  resources :lib_companies

  resources :feedbacks
  match '/admin/hourscan'  =>'admin#hourscan',:as=>:adminhourscan
  match '/admin/hourscaninfo'  =>'admin#hourscaninfo',:as=>:adminhourscaninfo  
  match '/admin/move'  =>'admin#move',:as=>:adminmove
  match '/admin/moveinfo'  =>'admin#moveinfo',:as=>:adminmoveinfo  
  match '/admin/quzhougrasp'  =>'admin#quzhougrasp',:as=>:adminquzhougrasp
  match '/admin/tf56grasp'  =>'admin#tf56grasp',:as=>:admintf56grasp
  match '/admin/cargo_manage'  =>'admin#cargo_manage',:as=>:admincargo_manage
  match '/admin/stockcargo_manage'  =>'admin#stockcargo_manage' ,:as=>:adminstockcargo_manage
  match '/admin/truck_manage'  =>'admin#truck_manage',:as=>:admintruck_manage
  match '/admin/stocktruck_manage'  =>'admin#stocktruck_manage',:as=>:adminstocktruck_manage
  match '/admin/quote_manage'  =>'admin#quote_manage',:as=>:adminquote_manage
  match '/admin/usercontact_manage'  =>'admin#usercontact_manage',:as=>:adminusercontact_manage
  match '/admin/company_manage  '  =>'admin#company_manage' ,:as=>:admincompany_manage
  match '/admin/get_room_contact' =>'admin#get_room_contact' ,:as=>:admin_get_room_contact
  match '/admin/show_room_contact' =>'admin#show_room_contact' ,:as=>:admin_show_room_contact
  match '/admin/grasp_tf56' =>'admin#grasp_tf56' ,:as=>:admin_grasp_tf56
  match '/admin/grasp_quzhou' =>'admin#grasp_quzhou' ,:as=>:admin_grasp_quzhou
  match '/admin/scan' =>'admin#scan' ,:as=>:admin_scan
  match '/admin/scaninfo' =>'admin#scan_info' ,:as=>:admin_scan_info
  match '/admin/show_cron_mail' =>'admin#show_cron_mail' ,:as=>:admin_show_cron_mail
  match 'admin/daily_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#daily_trends' ,:as=>:admin_daily_trends
  match 'admin/hourly_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#hourly_trends' ,:as=>:admin_daily_trends
  match '/admin/request_log_analysis((/all/:all)(/logfile/:logfile))' =>'admin#request_log_analysis' ,:as=>:admin_request_log_analysis
  match '/admin/show_log(/logfile/:logfile)' =>'admin#show_log' ,:as=>:admin_show_log
  match '/admin/backup_db' =>'admin#backup_db' ,:as=>:admin_backup_db
  get "admin/index"

  resources :citystatistics

  get "quzhou_wuliu/index"
  get "quzhou_wuliu/show"

  match '/scans/uinfoscan'  =>'scans#uinfoscan',:as=>:scanuinfoscan
  match '/scans/expiretimer'  =>'scans#expiretimer',:as=>:scanexpiretimer
  match '/scans/truckexpire'  =>'scans#truckexpire',:as=>:scantruckexpire
  match '/scans/cargoexpire'  =>'scans#cargoexpire',:as=>:scancargoexpire
  match '/scans/scan'  =>'scans#scan',:as=>:scanscan
  match '/scans/scaninfo'  =>'scans#scaninfo',:as=>:scaninfo
  resources :scans

  resources :lstatistics

  resources :ustatistics

  resources :tstatistics

  resources :cstatistics

  match '/trucks/quoteinquery/:truck_id' =>'trucks#quoteinquery',:as=>:truckquoteinquery
  match '/cargos/quoteinquery/:cargo_id' =>'cargos#quoteinquery',:as=>:cargoquoteinquery
  match '/trucks/:truck_id/cargos/:cargo_id/inqueries/new'  =>'inqueries#new',:as=>:inquerienew
  match '/trucks/:truck_id/inqueries/truck' =>'inqueries#truck', :as=>:inquerietruck
  match '/cargos/:cargo_id/inqueries/cargo' =>'inqueries#cargo', :as=>:inqueriescargo
  match '/users/:user_id/inqueries/tome/:to' =>'inqueries#index',:as=>:inqueriesto
    match "/cargos/request_chenjiao/:id" =>'cargos#request_chenjiao',:as=>:cargorequest_chenjiao
  match "/trucks/confirm_chenjiao/:id" =>'trucks#confirm_chenjiao',:as=>:trucksconfirm_chenjiao
  resources :inqueries
  match '/cargos/search(/:from/:to(/:page))'  =>'cargos#search',:as=>:cargossearchline
  match '/cargos/:cargo_id/trucks/:truck_id/quotes/new'  =>'quotes#new',:as=>:quotesnew
  match '/cargos/:cargo_id/quotes/cargo' =>'quotes#cargo', :as=>:quotescargo
  match '/trucks/:truck_id/quotes/truck' =>'quotes#truck', :as=>:quotestruck
  match 'users/:user_id/quotes/tome/:to' =>'quotes#index',:as=>:quotesto
  resources :quotes

  resources :line_ads

  match 'searches/:user_id/:stype/' =>'searches#new',:as=>:searchespublicnew

  resources :searches

  get "public_main/index"


  match 'users/login' => 'users#login', :as => :userslogin
  match 'cargos/public' =>'cargos#public',:as=>:cargospublic
  match 'trucks/public' =>'trucks#public',:as=>:truckspublic

  match '/trucks/search/:from/:to/:page'  =>'trucks#search',:as=>:truckssearchline
  match '/trucks/request_chenjiao/:id' =>"trucks#request_chenjiao" ,:as=>:trucksrequest_chenjiao
  match '/trucks/index/:status' =>"trucks#index" ,:as=>:truckindexstatus
  match  '/trucks/new'=>'trucks#new',:as=>:trucksnew
  match  '/trucks/create'=>'trucks#create',:as=>:truckscreate
  match '/trucks/show' =>'trucks#show',:as=>:trucksshow
  match '/trucks/list/:id'=>'trucks#index',:as=>:trucksindex
  match '/trucks/:truck_id/match' =>'trucks#match', :as=>:trucksmatch
  resources :trucks do
    resources :inqueries
    resources :quotes
  end
  match '/companies/new/(:who)' =>'companies#new',:as=>:companiesnewwho
  match '/companies/index/:id(/:who)' =>'companies#index',:as=>:companiesindex
  match '/companies/showf/:id' =>'companies#showf',:as=>:companiesshowf
  match '/companies/show/:id/(:who)' =>'companies#show',:as=>:companiesshow
  match '/companies/search' =>'companies#search',:as=>:companiessearch
  match '/companies/create' =>'companies#create',:as=>:companiescreate
  match '/companies/admin' =>'companies#admin',:as=>:companiesadmin
  resources :companies

  match '/stock_trucks/:stock_truck_id/trucks/part' =>'trucks#part', :as=>:truckspart
  match  '/stock_trucks/oper/:id' =>'stock_trucks#oper',:as=>:stock_trucksoper
  match '/stock_trucks/create' =>'stock_trucks#create',:as=>:stock_truckscreate
  resources :stock_trucks do
    resources :trucks
  end

  match '/stock_cargos/:stock_cargo_id/cargos/part' =>'cargos#part', :as=>:cargospart
  match  '/stock_cargos/create' =>'stock_cargos#create', :as=>:stock_cargoscreate

  resources :stock_cargos  do
    resources :cargos
  end

  match 'cargos/request_chenjiao/:id'=>"cargos#request_chenjiao" ,:as=>:cargorequest_chenjiao
  match '/cargos/index/:status' =>"cargos#index" ,:as=>:cargoindexstatus
  match '/cargos/search' =>'cargos#search', :as=>:cargosrootsearch
  match '/cargos/new' =>'cargos#new', :as=>:cargosnew
  match '/cargos/create' =>'cargos#create', :as=>:cargoscreate
  match '/cargos/show' =>'cargos#show', :as=>:cargosshow
  match '/cargos/list/:id' =>'cargos#index', :as=>:cargosindex
  match '/cargos/:cargo_id/match' =>'cargos#match', :as=>:cargosmatch
  match '/cargos/destroy/:id' =>'cargos#destroy', :as=>:cargosdestroy
  
  resources :cargos do
    resources :quotes
    resources :inqueries
  end


  match  '/package_categories/show/:code' =>'package_categories#show',:as=>:package_categoriesshow
  resources :package_categories
  match '/user_contacts/showf/:id'=>'user_contacts#showf' , :as=>:usercontactsshowf
  match '/user_contacts/index/:id/(:who)'=>'user_contacts#index' , :as=>:usercontactsindex
  match '/user_contacts/user/:user_id'=>'user_contacts#show' , :as=>:usercontactsshow
  match '/user_contacts/edit'=>'user_contacts#edit' , :as=>:usercontactsedit
  match '/user_contacts/create' =>'user_contacts#create', :as=>:usercontactscreate
  resources :user_contacts

  match '/cargo_categories/show/:code'=>'cargo_categories#show',:as=>:cargo_categoriesshow
  resources :cargo_categories


  match '/cities/:dir(/:code)'=>'cities#index',:as=>:citiesindex
  resources :cities
  
  match 'users/contact' =>'users#contact',:as=>:userscontact
  match 'users/about' =>'users#about',:as=>:usersabout
  match 'users/mianze' =>'users#mianze',:as=>:usersmianze
  match 'users/login' =>'users#login',:as=>:userslogin
  match 'users/logout' =>'users#logout',:as=>:userslogout
  match 'users/pwreset' =>'users#pwreset',:as=>:userspwreset
  match 'users/authenticate' =>'users#authenticate',:as=>:usersauthenticate
  match '/users/activate/:name/:code' =>'users#activate',:as=>:usersactivate
  match '/users/pw_sent_confirm' =>'users#pw_sent_confirm',:as=>:userspwsentconfirm
  match '/users/pw_reset_request' =>'users#pw_reset_request',:as=>:userspwresetrequest
  match '/users/change_password_confirm/:username/:activate' =>'users#change_password_confirm',:as=>:usersactivate
  resources :users do
    resources :stock_cargos
    resources :stock_trucks
    resources :cargos
    resources :trucks
    resources :quotes
    resources :inqueries
    resources :companies
    resources :searchs
    resources :contact_people
  end











  root :to => "cargos#search"


  match ':controller(/:action(/:id(.:format)))'

end

app/models/line_ad.rb
class LineAd
   include Mongoid::Document
   include Mongoid::Timestamps
      field :line,:type=>String
      field :fcity_name,:type=>String
      field :tcity_name,:type=>String
      field :company_name,:type=>String
      field :url,:type=>String
      field :one_word,:type=>String
      field :contact_phone,:type=>String
      field :user_id
      field :company_id
      field :lstatistic_id

end

app/controllers/line_ads_controller.rb
class LineAdsController < ApplicationController
  # GET /line_ads
  # GET /line_ads.xml
    layout nil
  def index
    @line_ads = LineAd.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @line_ads }
    end
  end

  # GET /line_ads/1
  # GET /line_ads/1.xml
  def show
    @line_ad = LineAd.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @line_ad }
    end
  end

  # GET /line_ads/new
  # GET /line_ads/new.xml
  def new
    @line_ad = LineAd.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @line_ad }
    end
  end

  # GET /line_ads/1/edit
  def edit
    @line_ad = LineAd.find(params[:id])
  end

  # POST /line_ads
  # POST /line_ads.xml
  def create
    @line_ad = LineAd.new(params[:line_ad])

    respond_to do |format|
      if @line_ad.save
        format.html { redirect_to(@line_ad, :notice => 'Line ad was successfully created.') }
        format.xml  { render :xml => @line_ad, :status => :created, :location => @line_ad }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @line_ad.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /line_ads/1
  # PUT /line_ads/1.xml
  def update
    @line_ad = LineAd.find(params[:id])

    respond_to do |format|
      if @line_ad.update_attributes(params[:line_ad])
        format.html { redirect_to(@line_ad, :notice => 'Line ad was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @line_ad.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /line_ads/1
  # DELETE /line_ads/1.xml
  def destroy
    @line_ad = LineAd.find(params[:id])
    @line_ad.destroy

    respond_to do |format|
      format.html { redirect_to(line_ads_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/line_ads_helper.rb
module LineAdsHelper
end

app/views/line_ads/_form.html.erb
<%= form_for(@line_ad) do |f| %>
  <% if @line_ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_ad.errors.count, "error") %> prohibited this line_ad from being saved:</h2>

      <ul>
      <% @line_ad.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :line %><br />
    <%= f.text_field :line %>
  </div>
  <div class="field">
    <%= f.label :fcity_name %><br />
    <%= f.text_field :fcity_name %>
  </div>
  <div class="field">
    <%= f.label :tcity_name %><br />
    <%= f.text_field :tcity_name %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :one_word %><br />
    <%= f.text_field :one_word %>
  </div>
  <div class="field">
    <%= f.label :contact_phone %><br />
    <%= f.text_field :contact_phone %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br />
    <%= f.text_field :company_id %>
  </div>
  <div class="field">
    <%= f.label :lstatistic_id %><br />
    <%= f.text_field :lstatistic_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_ads/edit.html.erb
<h1>Editing line_ad</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_ad %> |
<%= link_to 'Back', line_ads_path %>

app/views/line_ads/index.html.erb
<h1>Listing line_ads</h1>

<table>
  <tr>
    <th>Line</th>
    <th>Fcity name</th>
    <th>Tcity name</th>
    <th>Company name</th>
    <th>Url</th>
    <th>One word</th>
    <th>Contact phone</th>
    <th>User</th>
    <th>Company</th>
    <th>Lstatistic</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_ads.each do |line_ad| %>
  <tr>
    <td><%= line_ad.line %></td>
    <td><%= line_ad.fcity_name %></td>
    <td><%= line_ad.tcity_name %></td>
    <td><%= line_ad.company_name %></td>
    <td><%= line_ad.url %></td>
    <td><%= line_ad.one_word %></td>
    <td><%= line_ad.contact_phone %></td>
    <td><%= line_ad.user_id %></td>
    <td><%= line_ad.company_id %></td>
    <td><%= line_ad.lstatistic_id %></td>
    <td><%= link_to 'Show', line_ad %></td>
    <td><%= link_to 'Edit', edit_line_ad_path(line_ad) %></td>
    <td><%= link_to 'Destroy', line_ad, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line ad', new_line_ad_path %>

app/views/line_ads/new.html.erb
<h1>New line_ad</h1>

<%= render 'form' %>

<%= link_to 'Back', line_ads_path %>

app/views/line_ads/show.html.erb
<div class="ads">
  <%unless @line_ad.nil?%>
<a href=<%=@line_ad.url%>>

  <%= @line_ad.fcity_name %>
     <==>
  <%= @line_ad.tcity_name %>
 
  <%= @line_ad.company_name %>

  <%= @line_ad.one_word %>

  <%= @line_ad.contact_phone %>
</a>
  <%end%>
</div>






<%#= link_to 'Edit', edit_line_ad_path(@line_ad) %> 
<%#= link_to 'Back', line_ads_path %>