config/routes.rb
G0::Application.routes.draw do

  match '/mail_accounts/index(/:test_mail)'  =>'mail_accounts#index',:as=>:mail_account_index
  match '/mail_accounts/tuiguang((/mode/:mode/way/sent)(/domain/:domain))'  =>'mail_accounts#tuiguang',:as=>:mail_account_tuiguang
  match '/mail_accounts/tuiguang/((/mode/:mode/way/receive)(/domain/:domain))'  =>'mail_accounts#receive',:as=>:mail_account_receive
  resources :mail_accounts

  resources :lib_companies

  resources :feedbacks
  match '/admin/hourscan'  =>'admin#hourscan',:as=>:adminhourscan
  match '/admin/hourscaninfo'  =>'admin#hourscaninfo',:as=>:adminhourscaninfo  
  match '/admin/move'  =>'admin#move',:as=>:adminmove
  match '/admin/moveinfo'  =>'admin#moveinfo',:as=>:adminmoveinfo  
  match '/admin/quzhougrasp'  =>'admin#quzhougrasp',:as=>:adminquzhougrasp
  match '/admin/tf56grasp'  =>'admin#tf56grasp',:as=>:admintf56grasp
  match '/admin/cargo_manage'  =>'admin#cargo_manage',:as=>:admincargo_manage
  match '/admin/stockcargo_manage'  =>'admin#stockcargo_manage' ,:as=>:adminstockcargo_manage
  match '/admin/truck_manage'  =>'admin#truck_manage',:as=>:admintruck_manage
  match '/admin/stocktruck_manage'  =>'admin#stocktruck_manage',:as=>:adminstocktruck_manage
  match '/admin/quote_manage'  =>'admin#quote_manage',:as=>:adminquote_manage
  match '/admin/usercontact_manage'  =>'admin#usercontact_manage',:as=>:adminusercontact_manage
  match '/admin/company_manage  '  =>'admin#company_manage' ,:as=>:admincompany_manage
  match '/admin/get_room_contact' =>'admin#get_room_contact' ,:as=>:admin_get_room_contact
  match '/admin/show_room_contact' =>'admin#show_room_contact' ,:as=>:admin_show_room_contact
  match '/admin/grasp_tf56' =>'admin#grasp_tf56' ,:as=>:admin_grasp_tf56
  match '/admin/grasp_quzhou' =>'admin#grasp_quzhou' ,:as=>:admin_grasp_quzhou
  match '/admin/scan' =>'admin#scan' ,:as=>:admin_scan
  match '/admin/scaninfo' =>'admin#scan_info' ,:as=>:admin_scan_info
  match '/admin/show_cron_mail' =>'admin#show_cron_mail' ,:as=>:admin_show_cron_mail
  match 'admin/daily_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#daily_trends' ,:as=>:admin_daily_trends
  match 'admin/hourly_trends/day/:day/table/:table(/field/:field/condition/:condition/value/:value)' =>'admin#hourly_trends' ,:as=>:admin_daily_trends
  match '/admin/request_log_analysis((/all/:all)(/logfile/:logfile))' =>'admin#request_log_analysis' ,:as=>:admin_request_log_analysis
  match '/admin/show_log(/logfile/:logfile)' =>'admin#show_log' ,:as=>:admin_show_log
  match '/admin/backup_db' =>'admin#backup_db' ,:as=>:admin_backup_db
  get "admin/index"

  resources :citystatistics

  get "quzhou_wuliu/index"
  get "quzhou_wuliu/show"

  match '/scans/uinfoscan'  =>'scans#uinfoscan',:as=>:scanuinfoscan
  match '/scans/expiretimer'  =>'scans#expiretimer',:as=>:scanexpiretimer
  match '/scans/truckexpire'  =>'scans#truckexpire',:as=>:scantruckexpire
  match '/scans/cargoexpire'  =>'scans#cargoexpire',:as=>:scancargoexpire
  match '/scans/scan'  =>'scans#scan',:as=>:scanscan
  match '/scans/scaninfo'  =>'scans#scaninfo',:as=>:scaninfo
  resources :scans

  resources :lstatistics

  resources :ustatistics

  resources :tstatistics

  resources :cstatistics

  match '/trucks/quoteinquery/:truck_id' =>'trucks#quoteinquery',:as=>:truckquoteinquery
  match '/cargos/quoteinquery/:cargo_id' =>'cargos#quoteinquery',:as=>:cargoquoteinquery
  match '/trucks/:truck_id/cargos/:cargo_id/inqueries/new'  =>'inqueries#new',:as=>:inquerienew
  match '/trucks/:truck_id/inqueries/truck' =>'inqueries#truck', :as=>:inquerietruck
  match '/cargos/:cargo_id/inqueries/cargo' =>'inqueries#cargo', :as=>:inqueriescargo
  match '/users/:user_id/inqueries/tome/:to' =>'inqueries#index',:as=>:inqueriesto
    match "/cargos/request_chenjiao/:id" =>'cargos#request_chenjiao',:as=>:cargorequest_chenjiao
  match "/trucks/confirm_chenjiao/:id" =>'trucks#confirm_chenjiao',:as=>:trucksconfirm_chenjiao
  resources :inqueries
  match '/cargos/search(/:from/:to(/:page))'  =>'cargos#search',:as=>:cargossearchline
  match '/cargos/:cargo_id/trucks/:truck_id/quotes/new'  =>'quotes#new',:as=>:quotesnew
  match '/cargos/:cargo_id/quotes/cargo' =>'quotes#cargo', :as=>:quotescargo
  match '/trucks/:truck_id/quotes/truck' =>'quotes#truck', :as=>:quotestruck
  match 'users/:user_id/quotes/tome/:to' =>'quotes#index',:as=>:quotesto
  resources :quotes

  resources :line_ads

  match 'searches/:user_id/:stype/' =>'searches#new',:as=>:searchespublicnew

  resources :searches

  get "public_main/index"


  match 'users/login' => 'users#login', :as => :userslogin
  match 'cargos/public' =>'cargos#public',:as=>:cargospublic
  match 'trucks/public' =>'trucks#public',:as=>:truckspublic

  match '/trucks/search/:from/:to/:page'  =>'trucks#search',:as=>:truckssearchline
  match '/trucks/request_chenjiao/:id' =>"trucks#request_chenjiao" ,:as=>:trucksrequest_chenjiao
  match '/trucks/index/:status' =>"trucks#index" ,:as=>:truckindexstatus
  match  '/trucks/new'=>'trucks#new',:as=>:trucksnew
  match  '/trucks/create'=>'trucks#create',:as=>:truckscreate
  match '/trucks/show' =>'trucks#show',:as=>:trucksshow
  match '/trucks/list/:id'=>'trucks#index',:as=>:trucksindex
  match '/trucks/:truck_id/match' =>'trucks#match', :as=>:trucksmatch
  resources :trucks do
    resources :inqueries
    resources :quotes
  end
  match '/companies/new/(:who)' =>'companies#new',:as=>:companiesnewwho
  match '/companies/index/:id(/:who)' =>'companies#index',:as=>:companiesindex
  match '/companies/showf/:id' =>'companies#showf',:as=>:companiesshowf
  match '/companies/show/:id/(:who)' =>'companies#show',:as=>:companiesshow
  match '/companies/search' =>'companies#search',:as=>:companiessearch
  match '/companies/create' =>'companies#create',:as=>:companiescreate
  match '/companies/admin' =>'companies#admin',:as=>:companiesadmin
  resources :companies

  match '/stock_trucks/:stock_truck_id/trucks/part' =>'trucks#part', :as=>:truckspart
  match  '/stock_trucks/oper/:id' =>'stock_trucks#oper',:as=>:stock_trucksoper
  match '/stock_trucks/create' =>'stock_trucks#create',:as=>:stock_truckscreate
  resources :stock_trucks do
    resources :trucks
  end

  match '/stock_cargos/:stock_cargo_id/cargos/part' =>'cargos#part', :as=>:cargospart
  match  '/stock_cargos/create' =>'stock_cargos#create', :as=>:stock_cargoscreate

  resources :stock_cargos  do
    resources :cargos
  end

  match 'cargos/request_chenjiao/:id'=>"cargos#request_chenjiao" ,:as=>:cargorequest_chenjiao
  match '/cargos/index/:status' =>"cargos#index" ,:as=>:cargoindexstatus
  match '/cargos/search' =>'cargos#search', :as=>:cargosrootsearch
  match '/cargos/new' =>'cargos#new', :as=>:cargosnew
  match '/cargos/create' =>'cargos#create', :as=>:cargoscreate
  match '/cargos/show' =>'cargos#show', :as=>:cargosshow
  match '/cargos/list/:id' =>'cargos#index', :as=>:cargosindex
  match '/cargos/:cargo_id/match' =>'cargos#match', :as=>:cargosmatch
  match '/cargos/destroy/:id' =>'cargos#destroy', :as=>:cargosdestroy
  
  resources :cargos do
    resources :quotes
    resources :inqueries
  end


  match  '/package_categories/show/:code' =>'package_categories#show',:as=>:package_categoriesshow
  resources :package_categories
  match '/user_contacts/showf/:id'=>'user_contacts#showf' , :as=>:usercontactsshowf
  match '/user_contacts/index/:id/(:who)'=>'user_contacts#index' , :as=>:usercontactsindex
  match '/user_contacts/user/:user_id'=>'user_contacts#show' , :as=>:usercontactsshow
  match '/user_contacts/edit'=>'user_contacts#edit' , :as=>:usercontactsedit
  match '/user_contacts/create' =>'user_contacts#create', :as=>:usercontactscreate
  resources :user_contacts

  match '/cargo_categories/show/:code'=>'cargo_categories#show',:as=>:cargo_categoriesshow
  resources :cargo_categories


  match '/cities/:dir(/:code)'=>'cities#index',:as=>:citiesindex
  resources :cities
  
  match 'users/contact' =>'users#contact',:as=>:userscontact
  match 'users/about' =>'users#about',:as=>:usersabout
  match 'users/mianze' =>'users#mianze',:as=>:usersmianze
  match 'users/login' =>'users#login',:as=>:userslogin
  match 'users/logout' =>'users#logout',:as=>:userslogout
  match 'users/pwreset' =>'users#pwreset',:as=>:userspwreset
  match 'users/authenticate' =>'users#authenticate',:as=>:usersauthenticate
  match '/users/activate/:name/:code' =>'users#activate',:as=>:usersactivate
  match '/users/pw_sent_confirm' =>'users#pw_sent_confirm',:as=>:userspwsentconfirm
  match '/users/pw_reset_request' =>'users#pw_reset_request',:as=>:userspwresetrequest
  match '/users/change_password_confirm/:username/:activate' =>'users#change_password_confirm',:as=>:usersactivate
  resources :users do
    resources :stock_cargos
    resources :stock_trucks
    resources :cargos
    resources :trucks
    resources :quotes
    resources :inqueries
    resources :companies
    resources :searchs
    resources :contact_people
  end











  root :to => "cargos#search"


  match ':controller(/:action(/:id(.:format)))'

end

app/controllers/citystatistics_controller.rb
class CitystatisticsController < ApplicationController
  # GET /citystatistics
  # GET /citystatistics.xml
  def index
    @citystatistics = Citystatistic.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @citystatistics }
    end
  end

  # GET /citystatistics/1
  # GET /citystatistics/1.xml
  def show
    @citystatistic = Citystatistic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @citystatistic }
    end
  end

  # GET /citystatistics/new
  # GET /citystatistics/new.xml
  def new
    @citystatistic = Citystatistic.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @citystatistic }
    end
  end

  # GET /citystatistics/1/edit
  def edit
    @citystatistic = Citystatistic.find(params[:id])
  end

  # POST /citystatistics
  # POST /citystatistics.xml
  def create
    @citystatistic = Citystatistic.new(params[:citystatistic])

    respond_to do |format|
      if @citystatistic.save
        format.html { redirect_to(@citystatistic, :notice => 'Citystatistic was successfully created.') }
        format.xml  { render :xml => @citystatistic, :status => :created, :location => @citystatistic }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @citystatistic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /citystatistics/1
  # PUT /citystatistics/1.xml
  def update
    @citystatistic = Citystatistic.find(params[:id])

    respond_to do |format|
      if @citystatistic.update_attributes(params[:citystatistic])
        format.html { redirect_to(@citystatistic, :notice => 'Citystatistic was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @citystatistic.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /citystatistics/1
  # DELETE /citystatistics/1.xml
  def destroy
    @citystatistic = Citystatistic.find(params[:id])
    @citystatistic.destroy

    respond_to do |format|
      format.html { redirect_to(citystatistics_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/citystatistics_helper.rb
module CitystatisticsHelper
end

app/views/citystatistics/_form.html.erb
<%= form_for(@citystatistic) do |f| %>
  <% if @citystatistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@citystatistic.errors.count, "error") %> prohibited this citystatistic from being saved:</h2>

      <ul>
      <% @citystatistic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cargo %><br />
    <%= f.text_field :cargo %>
  </div>
  <div class="field">
    <%= f.label :truck %><br />
    <%= f.text_field :truck %>
  </div>
  <div class="field">
    <%= f.label :stock_cargo %><br />
    <%= f.text_field :stock_cargo %>
  </div>
  <div class="field">
    <%= f.label :stock_truck %><br />
    <%= f.text_field :stock_truck %>
  </div>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :line %><br />
    <%= f.text_field :line %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/citystatistics/edit.html.erb
<h1>Editing citystatistic</h1>

<%= render 'form' %>

<%= link_to 'Show', @citystatistic %> |
<%= link_to 'Back', citystatistics_path %>

app/views/citystatistics/index.html.erb
<h1>Listing citystatistics</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Cargo</th>
    <th>Truck</th>
    <th>Stock cargo</th>
    <th>Stock truck</th>
    <th>User</th>
    <th>Company</th>
    <th>Line</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @citystatistics.each do |citystatistic| %>
  <tr>
    <td><%= citystatistic.code %></td>
    <td><%= citystatistic.name %></td>
    <td><%= citystatistic.cargo %></td>
    <td><%= citystatistic.truck %></td>
    <td><%= citystatistic.stock_cargo %></td>
    <td><%= citystatistic.stock_truck %></td>
    <td><%= citystatistic.user %></td>
    <td><%= citystatistic.company %></td>
    <td><%= citystatistic.line %></td>
    <td><%= link_to 'Show', citystatistic %></td>
    <td><%= link_to 'Edit', edit_citystatistic_path(citystatistic) %></td>
    <td><%= link_to 'Destroy', citystatistic, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Citystatistic', new_citystatistic_path %>

app/views/citystatistics/new.html.erb
<h1>New citystatistic</h1>

<%= render 'form' %>

<%= link_to 'Back', citystatistics_path %>

app/views/citystatistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @citystatistic.code %>
</p>

<p>
  <b>Name:</b>
  <%= @citystatistic.name %>
</p>

<p>
  <b>Cargo:</b>
  <%= @citystatistic.cargo %>
</p>

<p>
  <b>Truck:</b>
  <%= @citystatistic.truck %>
</p>

<p>
  <b>Stock cargo:</b>
  <%= @citystatistic.stock_cargo %>
</p>

<p>
  <b>Stock truck:</b>
  <%= @citystatistic.stock_truck %>
</p>

<p>
  <b>User:</b>
  <%= @citystatistic.user %>
</p>

<p>
  <b>Company:</b>
  <%= @citystatistic.company %>
</p>

<p>
  <b>Line:</b>
  <%= @citystatistic.line %>
</p>


<%= link_to 'Edit', edit_citystatistic_path(@citystatistic) %> |
<%= link_to 'Back', citystatistics_path %>